export const menuItems: string[] = [
  "Sausage",
  "Bread omelet dish",
  "Chicken salad pieces",
  "French fry fingers",
  "Sweety granola mix",
  "Onion ring",
  "Sandwich",
  "Fresh fish sticks",
  "Fresh salmon steak",
  "Grilled salmon meat",
  "Semi vegetable fry",
  "Burrito fry",
  "Baguette",
  "Hot fried noodles",
  "Hot sea fish curry",
  "Light fried chicken",
  "Vegetable sausage",
  "Fried chicken",
  "Bacon",
  "Ravioli pepper pieces",
  "Salt tomato noodles",
  "Semi fried dumplings",
  "Hamburger",
  "Muffin cake",
];
