// constants/products.ts
import { Product } from "@/interfaces";

export const products: Product[] = [
  {
    id: 1,
    name: "Sausage",
    description:
      "Juicy and flavorful sausages grilled to perfection, perfect as a snack or in a full meal.",
    price: 180.0,
    flavour: "Non veg",
    size: "250 grams",
    vendor: "MeatLovers",
    type: "Snack Foods",
    availability: true,
    image: "/assets/images/sausage.png",
  },
  {
    id: 2,
    name: "Bread Omelet Dish",
    description:
      "Fluffy omelet sandwiched in soft bread, seasoned with herbs and spices for a filling breakfast.",
    price: 150.0,
    flavour: "Non veg",
    size: "300 grams",
    vendor: "MorningMeals",
    type: "Breakfast",
    availability: true,
    image: "/assets/images/bread-omelet.png",
  },
  {
    id: 3,
    name: "Chicken Salad Pieces",
    description:
      "Tender chicken cubes tossed with crunchy vegetables, drizzled with a creamy dressing.",
    price: 199.0,
    flavour: "Non veg",
    size: "600 grams",
    vendor: "HealthyBites",
    type: "Salads",
    availability: true,
    image: "/assets/images/chicken-salad.png",
  },
  {
    id: 4,
    name: "French Fry Fingers",
    description:
      "Crispy golden potato fries with a crunchy exterior and fluffy inside, lightly salted.",
    price: 120.0,
    flavour: "Veg",
    size: "250 grams",
    vendor: "SnackHouse",
    type: "Snack Foods",
    availability: true,
    image: "/assets/images/fry-fingers.png",
  },
  {
    id: 5,
    name: "Sweety Granola Mix",
    description:
      "A crunchy mix of oats, honey, nuts, and dried fruits, perfect for a healthy snack.",
    price: 210.0,
    flavour: "Veg",
    size: "300 grams",
    vendor: "HealthyCrunch",
    type: "Snacks",
    availability: true,
    image: "/assets/images/sweety-granola.png",
  },
  {
    id: 6,
    name: "Onion Rings",
    description:
      "Golden-brown crispy onion rings served with a tangy dipping sauce.",
    price: 90.0,
    flavour: "Veg",
    size: "200 grams",
    vendor: "SnackHouse",
    type: "Snack Foods",
    availability: true,
    image: "/assets/images/onion-rings.png",
  },
  {
    id: 7,
    name: "Sandwich",
    description:
      "A wholesome sandwich layered with fresh vegetables, cheese, and choice of protein.",
    price: 160.0,
    flavour: "Veg / Non veg",
    size: "250 grams",
    vendor: "DailyEats",
    type: "Meals",
    availability: true,
    image: "/assets/images/sandwich.png",
  },
  {
    id: 8,
    name: "Fresh Fish Sticks",
    description:
      "Crispy breaded fish sticks served with tartar sauce, perfect for seafood lovers.",
    price: 200.0,
    flavour: "Non veg",
    size: "300 grams",
    vendor: "SeaDelights",
    type: "Seafood",
    availability: true,
    image: "/assets/images/fish-sticks.png",
  },
  {
    id: 9,
    name: "Fresh Salmon Steak",
    description:
      "Thick salmon steak, pan-seared with garlic butter and herbs for a rich taste.",
    price: 350.0,
    flavour: "Non veg",
    size: "400 grams",
    vendor: "SeaDelights",
    type: "Seafood",
    availability: true,
    image: "/assets/images/salmon-steak.png",
  },
  {
    id: 10,
    name: "Grilled Salmon Meat",
    description:
      "Delicate salmon fillet grilled with spices and lemon zest, packed with omega-3 goodness.",
    price: 266.0,
    flavour: "Non veg",
    size: "500 grams",
    vendor: "Prida",
    type: "Snack Foods",
    availability: true,
    image: "/assets/images/grilled-salmon.png",
  },
  {
    id: 11,
    name: "Semi Vegetable Fry",
    description:
      "A delicious stir-fry of fresh vegetables lightly seasoned for a healthy meal.",
    price: 140.0,
    flavour: "Veg",
    size: "250 grams",
    vendor: "VeggieLovers",
    type: "Meals",
    availability: true,
    image: "/assets/images/veg-fry.png",
  },
  {
    id: 12,
    name: "Burrito Fry",
    description:
      "Crispy fried burrito stuffed with beans, cheese, and veggies, served with salsa.",
    price: 220.0,
    flavour: "Veg / Non veg",
    size: "300 grams",
    vendor: "MexiBites",
    type: "Meals",
    availability: true,
    image: "/assets/images/burrito.png",
  },
  {
    id: 13,
    name: "Baguette",
    description:
      "Freshly baked French baguette with a golden crust and soft, airy inside.",
    price: 110.0,
    flavour: "Veg",
    size: "200 grams",
    vendor: "BakeryHouse",
    type: "Bakery",
    availability: true,
    image: "/assets/images/baguette.png",
  },
  {
    id: 14,
    name: "Hot Fried Noodles",
    description:
      "Stir-fried noodles with vegetables and spices for a hot and savory delight.",
    price: 180.0,
    flavour: "Veg / Non veg",
    size: "350 grams",
    vendor: "AsianEats",
    type: "Meals",
    availability: true,
    image: "/assets/images/fried-noodles.png",
  },
  {
    id: 15,
    name: "Hot Sea Fish Curry",
    description:
      "Spicy fish curry cooked in coconut milk and aromatic spices, served hot.",
    price: 240.0,
    flavour: "Non veg",
    size: "400 grams",
    vendor: "SeaDelights",
    type: "Seafood",
    availability: true,
    image: "/assets/images/sea-fish.png",
  },
  {
    id: 16,
    name: "Light Fried Chicken",
    description:
      "Golden fried chicken with a crispy coating and tender juicy inside.",
    price: 260.0,
    flavour: "Non veg",
    size: "400 grams",
    vendor: "MeatLovers",
    type: "Chicken",
    availability: true,
    image: "/assets/images/light-fried-chicken.png",
  },
  {
    id: 17,
    name: "Vegetable Sausage",
    description:
      "A plant-based sausage made with fresh vegetables and spices, great for vegetarians.",
    price: 170.0,
    flavour: "Veg",
    size: "250 grams",
    vendor: "VeggieLovers",
    type: "Snack Foods",
    availability: true,
    image: "/assets/images/veg-fry.png",
  },
  {
    id: 18,
    name: "Fried Chicken",
    description:
      "Classic deep-fried chicken, seasoned with herbs and served crispy hot.",
    price: 270.0,
    flavour: "Non veg",
    size: "450 grams",
    vendor: "MeatLovers",
    type: "Chicken",
    availability: true,
    image: "/assets/images/fried-chicken.png",
  },
  {
    id: 19,
    name: "Bacon",
    description:
      "Crispy smoked bacon strips cooked until golden, perfect for breakfast or toppings.",
    price: 200.0,
    flavour: "Non veg",
    size: "250 grams",
    vendor: "MeatLovers",
    type: "Breakfast",
    availability: true,
    image: "/assets/images/bacon.png",
  },
  {
    id: 20,
    name: "Ravioli Pepper Pieces",
    description:
      "Soft pasta pockets filled with cheese and pepper, cooked in a rich tomato sauce.",
    price: 260.0,
    flavour: "Veg",
    size: "300 grams",
    vendor: "ItalianEats",
    type: "Pasta",
    availability: true,
    image: "/assets/images/fried-dumplings.png",
  },
  {
    id: 21,
    name: "Salt Tomato Noodles",
    description:
      "Noodles tossed in a light tomato sauce with a hint of salt and herbs.",
    price: 170.0,
    flavour: "Veg",
    size: "350 grams",
    vendor: "AsianEats",
    type: "Meals",
    availability: true,
    image: "/assets/images/tomato-noodles.png",
  },
  {
    id: 22,
    name: "Semi Fried Dumplings",
    description:
      "Juicy dumplings pan-fried to a golden crisp, served with soy dipping sauce.",
    price: 190.0,
    flavour: "Veg / Non veg",
    size: "300 grams",
    vendor: "AsianEats",
    type: "Snacks",
    availability: true,
    image: "/assets/images/fried-dumplings.png",
  },
  {
    id: 23,
    name: "Hamburger",
    description:
      "A juicy beef patty stacked with lettuce, tomato, cheese, and sauce inside a soft bun.",
    price: 300.0,
    flavour: "Non veg",
    size: "450 grams",
    vendor: "BurgerHouse",
    type: "Fast Food",
    availability: true,
    image: "/assets/images/hamburger.png",
  },
  {
    id: 24,
    name: "Muffin Cake",
    description:
      "Soft and fluffy muffin with a sweet buttery taste, perfect as a dessert or snack.",
    price: 100.0,
    flavour: "Veg",
    size: "150 grams",
    vendor: "BakeryHouse",
    type: "Bakery",
    availability: true,
    image: "/assets/images/muffin.png",
  },
];
